// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWD_A_201BuBxZcrBx8DHwm_rqbAL_jM0',
    appId: '1:301148462418:web:02bf6988be089d49db2e8b',
    messagingSenderId: '301148462418',
    projectId: 'clean-architecture-5cc89',
    authDomain: 'clean-architecture-5cc89.firebaseapp.com',
    storageBucket: 'clean-architecture-5cc89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyo2Ha-812RUYQF7j31fceJ_IIBuKzryY',
    appId: '1:301148462418:android:80db8f64fad6e96bdb2e8b',
    messagingSenderId: '301148462418',
    projectId: 'clean-architecture-5cc89',
    storageBucket: 'clean-architecture-5cc89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHRSfiznN09Qt9lP51aGTxL9R4Li7B3Bk',
    appId: '1:301148462418:ios:368378fc543d6cb5db2e8b',
    messagingSenderId: '301148462418',
    projectId: 'clean-architecture-5cc89',
    storageBucket: 'clean-architecture-5cc89.appspot.com',
    iosBundleId: 'com.example.cleanArchPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHRSfiznN09Qt9lP51aGTxL9R4Li7B3Bk',
    appId: '1:301148462418:ios:368378fc543d6cb5db2e8b',
    messagingSenderId: '301148462418',
    projectId: 'clean-architecture-5cc89',
    storageBucket: 'clean-architecture-5cc89.appspot.com',
    iosBundleId: 'com.example.cleanArchPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWD_A_201BuBxZcrBx8DHwm_rqbAL_jM0',
    appId: '1:301148462418:web:25f2c2fd20d3e570db2e8b',
    messagingSenderId: '301148462418',
    projectId: 'clean-architecture-5cc89',
    authDomain: 'clean-architecture-5cc89.firebaseapp.com',
    storageBucket: 'clean-architecture-5cc89.appspot.com',
  );
}
